package planfiles

import (
	"context"
	"errors"
	"net/url"
	"path"
	"sort"
	"strings"

	"go.uber.org/zap"

	"github.com/kandev/kandev/internal/planfiles/format"
	"github.com/kandev/kandev/internal/planfiles/scan"
	taskmodels "github.com/kandev/kandev/internal/task/models"
)

// indexMarker is the first line of a generated index. Only a file that starts
// with it is ever overwritten.
const indexMarker = "<!-- Generated by Kandev plan files. Do not edit. -->"

// indexStatusOrder is the closed order of the status sections.
var indexStatusOrder = []format.BoardStatus{
	format.BoardQueued, format.BoardInProgress, format.BoardWaitingOwner,
	format.BoardWaitingExternal, format.BoardDeferred, format.BoardDone,
}

// isIndexFile reports that relPath names the configured index file. An empty
// name means the index is off.
func isIndexFile(indexFile, relPath string) bool {
	return indexFile != "" && path.Base(relPath) == indexFile
}

// indexDir identifies one scanned directory of one repository.
type indexDir struct {
	repoID string
	dir    string
}

// writeIndexes writes the index file into every scanned directory that holds
// a visible plan file, after the board order of the pass has settled.
func (p *pass) writeIndexes(ctx context.Context, plans []tracked) {
	if p.cfg.IndexFile == "" || len(plans) == 0 {
		return
	}
	rank := p.boardRanks(ctx)
	groups := map[indexDir][]tracked{}
	for _, tr := range plans {
		key := indexDir{repoID: tr.entry.repo.ID, dir: path.Dir(tr.entry.relPath)}
		groups[key] = append(groups[key], tr)
	}
	keys := make([]indexDir, 0, len(groups))
	for key := range groups {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool {
		if keys[i].repoID != keys[j].repoID {
			return keys[i].repoID < keys[j].repoID
		}
		return keys[i].dir < keys[j].dir
	})
	for _, key := range keys {
		if p.dirUnreadable(key) {
			continue
		}
		content := p.renderIndex(groups[key], rank)
		p.writeIndex(key, []byte(content))
	}
}

// dirUnreadable reports that something under the directory could not be read
// this pass, so an index of it would be incomplete.
func (p *pass) dirUnreadable(key indexDir) bool {
	if _, ok := p.protectedRepos[key.repoID]; ok {
		return true
	}
	if _, ok := p.protectedPaths[pathKey(key.repoID, key.dir)]; ok {
		return true
	}
	prefix := pathKey(key.repoID, key.dir+"/")
	for k := range p.protectedPaths {
		if strings.HasPrefix(k, prefix) {
			return true
		}
	}
	return false
}

func (p *pass) writeIndex(key indexDir, content []byte) {
	rel := path.Join(key.dir, p.cfg.IndexFile)
	wrote, err := scan.WriteGenerated(p.roots[key.repoID], rel, content, indexMarker)
	switch {
	case errors.Is(err, scan.ErrNotGenerated):
		p.addError(key.repoID, rel, ReasonIndexNotOwned)
		incIndex(p.svc.logger, indexNotOwned)
	case err != nil:
		p.addError(key.repoID, rel, ReasonWriteFailed)
		p.svc.logger.Warn("plan file index write failed",
			zap.String("repository_id", key.repoID), zap.String("rel_path", rel), zap.Error(err))
	case wrote:
		incIndex(p.svc.logger, indexWritten)
	}
}

// boardRanks returns the board position of every task of the plan workflow:
// the order of its step, admitted tasks before queued ones. It is nil when
// the board cannot be read, and rows then follow their file order.
func (p *pass) boardRanks(ctx context.Context) map[string]int {
	tasks, err := p.svc.tasks.ListTasks(ctx, p.cfg.WorkflowID)
	if err != nil {
		p.degraded = true
		p.svc.logger.Warn("plan file index could not list tasks", zap.Error(err))
		return nil
	}
	byStep := map[string][]*taskmodels.Task{}
	for _, task := range tasks {
		byStep[task.WorkflowStepID] = append(byStep[task.WorkflowStepID], task)
	}
	ranks := make(map[string]int, len(tasks))
	for _, group := range byStep {
		sort.SliceStable(group, func(i, j int) bool {
			if ai, aj := isAdmitted(group[i]), isAdmitted(group[j]); ai != aj {
				return ai
			}
			return taskmodels.StepOrderLess(group[i], group[j])
		})
		for i, task := range group {
			ranks[task.ID] = i
		}
	}
	return ranks
}

func isAdmitted(task *taskmodels.Task) bool {
	return task.WIPAdmitted || task.QueuedForStepID != task.WorkflowStepID
}

// statusOf is the board status a plan is listed under: the one of the step its
// task holds, else the status its file names.
func (p *pass) statusOf(tr tracked) format.BoardStatus {
	if stepID := p.finalStep[tr.task.ID]; stepID != "" {
		for status, id := range p.cfg.StatusSteps {
			if id == stepID {
				return status
			}
		}
	}
	return tr.entry.file.Board
}

// renderIndex renders the index of one directory. It holds nothing that
// changes between passes over unchanged plans.
func (p *pass) renderIndex(plans []tracked, rank map[string]int) string {
	byStatus := map[format.BoardStatus][]tracked{}
	for _, tr := range plans {
		status := p.statusOf(tr)
		byStatus[status] = append(byStatus[status], tr)
	}
	var b strings.Builder
	b.WriteString(indexMarker + "\n\n# Plans\n")
	for _, status := range indexStatusOrder {
		group := byStatus[status]
		if len(group) == 0 {
			continue
		}
		sortIndexGroup(group, rank)
		b.WriteString("\n## " + string(status) + "\n\n")
		b.WriteString("| Plan | Priority | Executor | Date |\n| --- | --- | --- | --- |\n")
		for _, tr := range group {
			b.WriteString(indexRow(tr.entry))
		}
	}
	return b.String()
}

func sortIndexGroup(group []tracked, rank map[string]int) {
	sort.SliceStable(group, func(i, j int) bool {
		ri, iok := rank[group[i].task.ID]
		rj, jok := rank[group[j].task.ID]
		if iok && jok && ri != rj {
			return ri < rj
		}
		if iok != jok {
			return iok
		}
		a, b := group[i].entry, group[j].entry
		if ka, kb := a.orderKey(), b.orderKey(); ka.less(kb) || kb.less(ka) {
			return ka.less(kb)
		}
		return a.relPath < b.relPath
	})
}

func indexRow(e planEntry) string {
	return "| [" + cellText(e.file.Title) + "](" + linkTarget(path.Base(e.relPath)) + ") | " +
		cellText(e.file.Priority) + " | " + cellText(e.file.Executor) + " |  |\n"
}

var cellEscaper = strings.NewReplacer(
	`\`, `\\`, "|", `\|`, "[", `\[`, "]", `\]`, "`", "\\`", "<", `\<`, ">", `\>`,
)

// cellText reduces file text to one line and escapes what would break a table
// cell or a link label.
func cellText(s string) string {
	return cellEscaper.Replace(oneLine(s))
}

var linkEscaper = strings.NewReplacer("(", "%28", ")", "%29")

// linkTarget percent-encodes a file name for a Markdown link destination.
func linkTarget(name string) string {
	return linkEscaper.Replace(url.PathEscape(name))
}
